language: rust

os:
  - linux

# If you change this, you must also change README and Common.mk
rust:
  - nightly-2016-07-29

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-embedded
  - cargo install rustfmt
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      find -path ./extern -prune -o -name '*.rs' -exec rustfmt --write-mode=diff {} +; fi
  - make -C golf

