[package]
name = "nrf_pca10028"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>", "Philip Levis <pal@cs.stanford.edu>"]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[dependencies]
rust-libcore = "*"
common = { path = "../../common" }
cortexm0 = { path = "../../arch/cortex-m0" }
drivers = { path = "../../drivers" }
hil = { path = "../../hil" }
main = { path = "../../main" }
nrf51 = { path = "../../chips/nrf51" }
support = { path = "../../support" }
