[package]
name = "golf2"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>"]

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[dependencies]
capsules = { path = "../tock/capsules" }
hotel = { path = "../hotel" }
kernel = { path = "../tock/kernel" }
