[package]
name = "hotel"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>"]

build = "build.rs"

[dependencies]
rust-libcore = "*"
kernel = { git = "https://github.com/helena-project/tock" }
cortexm3 = { path = "../src/arch/cortex-m3" }
