[package]
name = "hotel"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>"]

build = "build.rs"

[dependencies]
kernel = { path = "../tock/kernel" }
cortexm3 = { path = "../tock/arch/cortex-m3" }
aligned="0.2.0"

