[package]
name = "nrf51"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>", "Philip Levis <pal@cs.stanford.edu>"]

build = "build.rs"

[dependencies]
rust-libcore = "*"
common = { path = "../../common" }
cortexm0 = { path = "../../arch/cortex-m0" }
hil = { path = "../../hil" }
main = { path = "../../main" }

[build-dependencies]
gcc = "0.3"
