[package]
name = "hotel"
version = "0.1.0"
authors = ["Amit Levy <amit@amitlevy.com>"]

build = "build.rs"

[dependencies]
rust-libcore = "*"
common = { path = "../../common" }
cortexm3 = { path = "../../arch/cortex-m3" }
hil = { path = "../../hil" }
main = { path = "../../main" }
